### ISSUE TITLE
@newrelic/security-agent v1.1.0 grpc instrumentation breaks New Relic agent instrumentation

### ISSUE THREAD

**Issue by bizob2828** [newrelic/csec-node-agent#192]
## Steps to Reproduce
 1. Clone https://github.com/newrelic/node-newrelic
 2. `npm ci`
 3. `NEW_RELIC_SECURITY_AGENT_ENABLED=true npm run versioned:internal:major grpc-js`

## Expected Behavior
All agent instrumentation versioned tests still pass with security agent.

## Additional context
It looks like the instrumentation in security agent is stomping on the Node.js agent.  We request that you back out grpc-js instrumentation and re-release until you can fix this bug.

**Comment by sumitsuthar** [comment]
Here is the link of versioned test.
https://github.com/k2io/node-newrelic-fork/actions/runs/8372881827
 Drafted PR to update @newrelic/security-agent.
 https://github.com/newrelic/node-newrelic/pull/2092
