### ISSUE TITLE
Agent crashing since latest rease. 

### ISSUE THREAD

**Issue by p13lgst** [newrelic/csec-node-agent#265]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description

I installed the newrelic node agent which installed the latest release (2.1.0) of this package, but it crashed on execution due to [this change](https://github.com/newrelic/csec-node-agent/pull/247/files#diff-19f0e54591149fa07d46752bbdda692d6c271c34566032ace45b770b8333754c). 

This causes a crash at the setLogger [below](https://github.com/newrelic/csec-node-agent/blob/fc528adf7b5a7f68a982c6329a52697e161cd3ca/lib/nr-security-agent/lib/core/health-check.js#L205) since it's trying to reassign a constant

## Relevant Logs / Console output

![image](https://github.com/user-attachments/assets/0c0bda44-480d-47f2-89df-c55462cfcc68)

[NOTE]: # ( Please provide specifics of the local error logs, Browser Dev Tools console, etc. if appropriate and possible. )

## Your Environment

[TIP]:  # ( Include as many relevant details about your environment as possible. )

Ubuntu 24.10, Node 20

**Comment by sumitsuthar** [comment]
Thanks for point out the issue..We will fix this asap
