### ISSUE TITLE
`npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.`

### ISSUE THREAD

**Issue by isaacbowen** [newrelic/csec-node-agent#56]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description

```
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
```

This package depends on a deprecated version of uuid, which is raising warnings during `npm install`.

Discovered this while attempting to upgrade from newrelic@10.2.0 to 10.3.0, which introduces a new dependency on @newrelic/security-agent.

## Steps to Reproduce

```sh
npm install @newrelic/security-agent@latest
```

## Expected Behavior

No deprecation warnings.

## Relevant Logs / Console output

Ran the following in a directory with no previous `node_modules` present.

```sh
➜ npm install @newrelic/security-agent@latest
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.

added 163 packages in 9s
```

## Your Environment

not relevant

## Additional context

n/a

**Comment by sumitsuthar** [comment]
Fix is provided in @newrelic/security-agent v0.1.3
